# Generated by Django 3.1.6 on 2021-02-17 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('respuesta', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preguntas',
            new_name='Pregunta',
        ),
        migrations.DeleteModel(
            name='Certificados',
        ),
        migrations.DeleteModel(
            name='Respuestas',
        ),
    ]
